In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


docs_task1 = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]


tfidf_vectorizer = TfidfVectorizer()
vector_matrix = tfidf_vectorizer.fit_transform(docs_task1)
cosine_sim_matrix = cosine_similarity(vector_matrix)


df_cosine = pd.DataFrame(data=cosine_sim_matrix, index=docs_task1, columns=docs_task1)
display(df_cosine)

,This is the first document.,This document is the second document.,And this is the third one.,Is this the first document?
This is the first document.,1.000000,0.646926,0.307772,1.000000
This document is the second document.,0.646926,1.000000,0.225240,0.646926
And this is the third one.,0.307772,0.225240,1.000000,0.307772
Is this the first document?,1.000000,0.646926,0.307772,1.000000

In [2]:

docs_task2 = [
    'data science is one of the most important fields of science',
    'this is one of the best data science courses',
    'data scientists analyze data'
]


tfidf_task2 = TfidfVectorizer()
matrix_task2 = tfidf_task2.fit_transform(docs_task2)


df_tfidf = pd.DataFrame(matrix_task2.toarray(), columns=tfidf_task2.get_feature_names_out())
display(df_tfidf)

,analyze,best,courses,data,fields,important,is,most,of,one,science,scientists,the,this
0,0.000000,0.000000,0.000000,0.189526,0.320895,0.320895,0.244049,0.320895,0.488098,0.244049,0.488098,0.000000,0.244049,0.000000
1,0.000000,0.400294,0.400294,0.236420,0.000000,0.000000,0.304434,0.000000,0.304434,0.304434,0.304434,0.000000,0.304434,0.400294
2,0.542701,0.000000,0.000000,0.641055,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.542701,0.000000,0.000000

In [6]:
import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize
import gensim

nltk.download('punkt')
nltk.download('punkt_tab')


df_simpsons = pd.read_csv('simpsons_script_lines.csv', engine='python', on_bad_lines='skip')
df_simpsons = df_simpsons.dropna(subset=['spoken_words'])


def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text

df_simpsons['cleaned_words'] = df_simpsons['spoken_words'].apply(clean_text)


print("Tokenizing... (This may take a minute)")
tokens = [word_tokenize(sentence) for sentence in df_simpsons['cleaned_words']]


print("Training Word2Vec Model...")
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)
print("Model Trained Successfully!")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Tokenizing... (This may take a minute)
Training Word2Vec Model...
Model Trained Successfully!

In [7]:

print("Words similar to 'homer':")
print(Skip_gram_model.wv.most_similar('homer'))

print("\nWords similar to 'marge':")
print(Skip_gram_model.wv.most_similar('marge'))

print("\nWords similar to 'bart':")
print(Skip_gram_model.wv.most_similar('bart'))

Words similar to 'homer':
[('abe', 0.8830363154411316), ('marge', 0.844245970249176), ('bartholomew', 0.822157621383667), ('bart', 0.8187345862388611), ('grampa', 0.8091992735862732), ('becky', 0.8059209585189819), ('jay', 0.7973824739456177), ('mindy', 0.7940530776977539), ('jessica', 0.7927207946777344), ('apu', 0.7920029759407043)]

Words similar to 'marge':
[('homer', 0.844245970249176), ('abe', 0.8367054462432861), ('becky', 0.8285139203071594), ('lisa', 0.8277841806411743), ('honey', 0.8192846179008484), ('sweetheart', 0.8141850233078003), ('sweetie', 0.8078082799911499), ('neddy', 0.8016130924224854), ('jessica', 0.7984387278556824), ('allison', 0.7982237935066223)]

Words similar to 'bart':
[('milhouse', 0.8806878924369812), ('lisa', 0.86533522605896), ('abe', 0.8551316857337952), ('grampa', 0.8437016010284424), ('jessica', 0.837863028049469), ('sweetie', 0.8332916498184204), ('maggie', 0.8239275813102722), ('luann', 0.8211967945098877), ('homer', 0.8187344670295715), ('kirk', 0.8181405067443848)]

In [8]:

print("Odd one out of ['jimbo', 'milhouse', 'kearney']:")
print(Skip_gram_model.wv.doesnt_match(['jimbo', 'milhouse', 'kearney']))

print("\nOdd one out of ['nelson', 'bart', 'milhouse']:")
print(Skip_gram_model.wv.doesnt_match(['nelson', 'bart', 'milhouse']))

print("\nOdd one out of ['homer', 'patty', 'selma']:")
print(Skip_gram_model.wv.doesnt_match(['homer', 'patty', 'selma']))

Odd one out of ['jimbo', 'milhouse', 'kearney']:
milhouse

Odd one out of ['nelson', 'bart', 'milhouse']:
nelson

Odd one out of ['homer', 'patty', 'selma']:
homer